a=str(input("Ho ten: "))
b=int(input("So ngay cong: "))
c=int(input("Don gia ngay cong: "))
d=float(input("He so phu cap: "))
e=int(input("Tam ung: "))
print("Nhan vien " + str(a) + ", Co tien luong=" + str(c*b*d) + ", Tam ung=" + str(e) + " va Thuc linh=" + str(c*b*d-e))